version: 0.2

phases:
  pre_build:
    commands:
      - echo "Iniciando Pre-build"      
      - aws s3 cp input/* s3://bucket-glue-incremental/input/
      - aws s3 cp scripts/main.py s3://bucket-glue-incremental/scripts/
      - table_name=$(echo `aws s3 ls s3://bucket-glue-incremental/input/`| cut -c 52-56)
      - echo $table_name
  build:
    commands:
      - echo "Iniciando a execução do job"
      - aws glue create-database
        --database-input "{\"Name\":\"tempdbteste\"}" --endpoint https://glue.us-east-1.amazonaws.com
