name: workflow_Glue_job1
on: workflow_dispatch
jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}} 
          aws-region: us-east-1

      - name: Deploy no S3
        env:
          BUCKET_NAME: bucket-glue-incremental
        run: | 
          aws s3 cp input/* s3://bucket-glue-incremental/input/a_processar/dados/
          aws s3 cp scripts/main.py s3://bucket-glue-incremental/scripts/
