name: workflow_Glue
on:
  push:
    branches:
      -  homologacao
      
jobs:
  trigger-workflow-homol:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Configure GitHub CLI
        env:
          GH_TOKEN: ${{ github.new_token_glue}}
        run: |
          gh auth login --with-token <<< "${{ secrets.TOKEN_GIT_SECRET}}"
      
      - name: Trigger Workflow homologacao
        run: |
          gh workflow run homologacao.yml

  trigger-workflow-desenvolvimento:
    runs-on: ubuntu-latest
    needs: trigger-workflow-homol

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Configure GitHub CLI
        env:
          GH_TOKEN: ${{ github.new_token_glue}}
        run: |
          gh auth login --with-token <<< "${{ secrets.TOKEN_GIT_SECRET}}"
          
      - name: Trigger Workflow desemvolvimento
        run: |
          gh workflow run desenvolvimento.yml

  trigger-workflow-producao:
    runs-on: ubuntu-latest
    needs: trigger-workflow-desenvolvimento

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Configure GitHub CLI
        env:
          GH_TOKEN: ${{ github.new_token_glue}}
        run: |
          gh auth login --with-token <<< "${{ secrets.TOKEN_GIT_SECRET}}"
          
      - name: Trigger Workflow producao
        run: |
          gh workflow run producao.yml
          

    
        
      
      
