name: workflow_Glue
on:
  push:
    branches:
      -  main
      
jobs:
  trigger-workflow1:
    runs-on: ubuntu-latest

    steps:
      - name: Configure GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.NEW_TOKEN }}
        run: |
          gh auth login --with-token <<< "${GH_TOKEN}"
      
      - name: Trigger Workflow 1
        run: |
          gh workflow run Job_1.yml

  trigger-workflow2:
    runs-on: ubuntu-latest
    needs: trigger-workflow1

    steps:
      - name: Configure GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.NEW_TOKEN }}
        run: |
          gh auth login --with-token <<< "${GH_TOKEN}"
          
      - name: Trigger Workflow 2
        run: |
          gh workflow run Job_2.yml
          

    
        
      
      
