name: workflow_Glue
on:
  push:
    branches:
      -  main
jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}} 
          aws-region: us-east-1

      - name: Deploy no S3
        env:
          BUCKET_NAME: bucket-glue-incremental
        run: | 
          aws s3 cp input/* s3://bucket-glue-incremental/input/
          aws s3 cp scripts/main.py s3://bucket-glue-incremental/scripts/
  
  job_2:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}} 
          aws-region: us-east-1
          
      - name: create glue database
        run: | 
          aws glue create-database --database-input "{\"Name\":\"Table_Etl_Teste\"}" --endpoint https://glue.us-east-1.amazonaws.com

      - name: create crawler
        run : |
          aws glue create-crawler --name crawlerteste --role arn:aws:iam::654654178935:role/service-role/AWSGlueServiceRole-testeelt 
          --database-name Table_Etl_Teste --targets "S3Targets=[{Path=s3://bucket-glue-incremental/input/}]"
          --schema-change-policy UpdateBehavior=LOG,DeleteBehavior=LOG
      
      - name : Start Crawler
        run : |
          aws glue start-crawler --name crawlerteste
    
        
      
      
