name: workflow_Glue
on:
  push:
    branches:
      -  main
      
jobs:
  trigger-workflow1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Configure GitHub CLI
        env:
          GH_TOKEN: ${{ github.new_token_glue}}
        run: |
          gh auth login --with-token <<< "${{ github.new_token_glue}}"
      
      - name: Trigger Workflow 1
        run: |
          gh workflow run Job_1.yml

  trigger-workflow2:
    runs-on: ubuntu-latest
    needs: trigger-workflow1

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Configure GitHub CLI
        env:
          GH_TOKEN: ${{ github.new_token_glue}}
        run: |
          gh auth login --with-token <<< "${{ github.new_token_glue}}}"
          
      - name: Trigger Workflow 2
        run: |
          gh workflow run job_2.yml

  trigger-workflow3:
    runs-on: ubuntu-latest
    needs: trigger-workflow2

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Configure GitHub CLI
        env:
          GH_TOKEN: ${{ github.new_token_glue}}
        run: |
          gh auth login --with-token <<< "${{ github.new_token_glue}}}"
          
      - name: Trigger Workflow 3
        run: |
          gh workflow run job_3.yml
          

    
        
      
      
