name: workflow_Glue
on:
  push:
    branches:
      -  main
      
jobs:
  trigger-workflow1:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Workflow 1
        run: |
          gh workflow run Job_1.yml

  trigger-workflow2:
    runs-on: ubuntu-latest
    needs: trigger-workflow1

    steps:
      - name: Trigger Workflow 2
        run: |
          gh workflow run Job_2.yml
          
  trigger-workflow3:
    runs-on: ubuntu-latest
    needs: trigger-workflow2

    steps:
      - name: Trigger Workflow 3
        run: |
          gh workflow run Job_3.yml

    
        
      
      
