name: workflow_Glue_job2
on: workflow_dispatch
jobs:
  job_2:
    runs-on: ubuntu-latest
    steps:     
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}} 
          aws-region: us-east-1
    

      - name: Start Glue Job 
        id: start_glue_job 
        run: |
          job_run_id=$(aws glue start-job-run --job-name ELT_JOB_BRONZE --query 'JobRunId' --output text ) 
          echo "JobRunId=$job_run_id" >> $GITHUB_ENV

      - name: Monitor Glue Job Status
        env:
          AWS_REGION: us-east-1
          JOB_NAME: 'ELT_JOB_BRONZE'
          JOB_RUN_ID: ${{ env.JobRunId }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          GIT_AUTHOR_NAME: ${{ github.actor }} 
          GIT_AUTHOR_EMAIL: ${{ github.actor }}@users.noreply.github.com 
          GIT_COMMITTER_NAME: ${{ github.actor }} 
          GIT_COMMITTER_EMAIL: ${{ github.actor }}@users.noreply.github.com
        run: |
          while true; do
            status=$(aws glue get-job-run --job-name "$JOB_NAME" --run-id "$JOB_RUN_ID" --query 'JobRun.Status' --output text) 
            echo "Current Job Status: $status" 
            if [ "$status" == "SUCCEEDED" ] || [ "$status" == "FAILED" ]; then 
              break 
            fi 
            echo "Waiting for the job to complete..." 
            sleep 30 
          done

          if [ "$status" == "SUCCEEDED" ]; then 
            echo "Job completed successfully!"
            echo "Executando push em desemvolvimento"

            aws s3 cp s3://bucket-glue-incremental/Homologacao/output_homol/ /input/
            git checkout desemvolvimento 
            git add .
            git commit -m 'Atualizando branch'
            git push origin desemvolvimento

          elif [ "$status" == "FAILED" ]; then 
            echo "Job failed." 
            exit 1
          fi 