name: workflow_Glue_job2
on: workflow_dispatch
jobs:
  job_2:
    runs-on: ubuntu-latest
    steps:     
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}} 
          aws-region: us-east-1
    

      - name: Start Glue Job 
        id: start_glue_job
        run: |
          JOB_NAME='ELT_JOB_BRONZE'
          job_run_id=$(aws glue start-job-run --job-name $JOB_NAME --query 'JobRunId' --output text) 
          get_status=$(aws glue get-job-run --job-name $JOB_NAME --run-id $job_run_id)
          status=$(echo $get_status | jq -r '.JobRun.JobRunState')
           while true; do
             if [ "$status" == "SUCCEEDED" ] || [ "$status" == "FAILED" ];then
               break
             fi
             echo "Waiting for the job to complete..." 
            sleep 30 
          done

          if [ "$status" == "SUCCEEDED" ]; then
            echo "Job completed successfully!"
                        
          elif [ "$status" == "FAILED" ]; then 
            echo "Job failed." 
            exit 1
          fi 
          
